### ISSUE TITLE
Race condition in startup?

### ISSUE THREAD

**Issue by markgould** [Particular/NServiceBus.Extensions.Hosting#23] opened 2019-11-19 16:18 UTC
I have a send only web endpoint that receives requests over HTTP and then sends commands (Integration with third-party)

If a request comes that injects the IMessageSession for the first time (This is running in an Azure App Service), I get an error saying "The message session can only be used after the endpoint is started. ". 

This continues to happen, unless I restart the site, and perform a request that doesn't use the IMessageSession, after that, everything appears to work correctly.

It does appear that the endpoint gets started, when I restart the app service I do see the following in the logs:

> INFO|NServiceBus.RunningEndpointInstance|Initiating shutdown.
INFO|NServiceBus.RunningEndpointInstance|Shutdown complete.

I'll try and setup a repro project.

Here's the stack trace:

> An unhandled exception was thrown by the application.  System.InvalidOperationException: The message session can only be used after the endpoint is started.     at NServiceBus.StartableEndpointWithExternallyManagedContainer.<.ctor>b__0_0()     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)  --- End of stack trace from previous location where exception was thrown ---     at System.Lazy`1.CreateValue()     at System.Lazy`1.get_Value()     at NServiceBus.HostBuilderExtensions.<>c__DisplayClass0_1.<UseNServiceBus>b__1(IServiceProvider _)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)     at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)     at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware)     at lambda_method(Closure , Object , HttpContext , IServiceProvider )     at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_1.<UseMiddleware>b__2(HttpContext context)     at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)     at TaxWeb.Integration.Infrastructure.RequestResponseLoggingMiddleware.Invoke(HttpContext context, IWebHostEnvironment environment) in F:\smiagent\_work\103\s\src\TaxWeb.Integration\Infrastructure\RequestResponseLoggingMiddleware.cs:line 50     at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by markgould** [comment] 2019-11-19 16:34
[repro.zip](https://github.com/Particular/NServiceBus.Extensions.Hosting/files/3864941/repro.zip)

Here's a repro. Does the call to UseNServiceBus have to come before ConfigureWebHostDefaults? If I do that, it does appear to work.

**Comment by dvdstelt** [comment] 2019-11-20 11:02
I would have to take a look, but I've got a full example working.

Here's the registration of NServiceBus inside ASP.NET Core 3.0 : dvdstelt/EventualConsistencyDemo:EventualConsistencyDemo/Program.cs@litedb#L27 
Here's the dependency injection part of LiteDb : dvdstelt/EventualConsistencyDemo:EventualConsistencyDemo/Startup.cs@litedb#L28 
Here's the handler inside ASP.NET that retrieves both SignalR Hub and LiteDb : dvdstelt/EventualConsistencyDemo:EventualConsistencyDemo/Handlers/OrderSubmissionHandler.cs@litedb#L20 

Note that it's in the litedb branch. On the master branch I'm only injecting SignalR atm.

Let me know if this solves your question, otherwise, I'd have to take a look at the repro.

**Comment by timbussmann** [comment] 2019-11-20 12:05
Hey @markgould , it seems like the sample starts working once `UseNServiceBus` is moved before `ConfigureWebHostDefaults`, can you confirm that?

**Comment by markgould** [comment] 2019-11-20 12:41
@dvdstelt I noticed in your project, you are not injecting an IMessageSession into any controller. If you inject an IMessageSession into your HomeController, you'll likely see the same issue I am running into, as I notice you call ConfigureWebHostDefaults before UseNServiceBus. 

@timbussmann yes, it does appear to work then. I also tested this in my actual application (inside VS). I'm about to deploy it to my test environment and run a few tests to confirm everything is working correctly.

**Comment by timbussmann** [comment] 2019-11-20 12:51
@markgould It looks like there is a race condition in case `UseNServiceBus` is specified after the ASP.NET configuration. Both "services" use an `IHostedService` to start up and the NServiceBus hosted service creates the `IMessageSession`. If the web host can start up and try to resolve a `IMessageSession` fast enough, it can't provide a valid message session yet. Due to the implementation using a `Lazy` internally, it then breaks that lazy and it will never return the session, even after NServiceBus is started. If the first request takes a little bit longer (e.g. Task.Delay(10) already resolved the issue), or doesn't request the message session right at the beginning, NServiceBus starts up in the meantime and can provide a working message session. This is unfortunate and I'll raise a dedicated issue for this soon.

In the meantime, I've raised [a doco PR ](https://github.com/Particular/docs.particular.net/pull/4598) to state that `UseNServiceBus` has to go first until this is fixed.

**Comment by markgould** [comment] 2019-11-20 12:58
@timbussmann Yep, that is what I was seeing! Thanks for verifying.

**Comment by dvdstelt** [comment] 2019-11-20 14:20
> @dvdstelt I noticed in your project, you are not injecting an IMessageSession into any controller. If you inject an IMessageSession into your HomeController, you'll likely see the same issue I am running into, as I notice you call ConfigureWebHostDefaults before UseNServiceBus.

It's in my [SignalR Hub](https://github.com/dvdstelt/EventualConsistencyDemo/blob/master/EventualConsistencyDemo/Hubs/TicketHub.cs#L13) but there it's requested very late.

Even though it worked, I [also changed it](https://github.com/dvdstelt/EventualConsistencyDemo/blob/litedb/EventualConsistencyDemo/Program.cs#L38) to make sure I don't get sudden issues in the future and have forgotten the problem! ;-)

**Comment by timbussmann** [comment] 2019-11-20 15:02
I've summarized the reason for the exception and some ideas in this issue here: https://github.com/Particular/NServiceBus.Extensions.Hosting/issues/24. Feel free to join the discussion @markgould. At this point, I'm hesitant to consider this a bug due to the fact that the strict ordering requirements are kind of expected behavior of the Microsoft generic host. There is no clear "fix" for this other than hacking around the natural behavior of the generic host to avoid such situations. Thoughts on that?

**Comment by markgould** [comment] 2019-11-21 13:16
I agree - I think as long as it's documented then we should be good. I'll be upgrading a few other web endpoints and I'll report back if I run into any issues.

I'm wondering if the DI registration also needs to be moved out of Startup.cs and moved to ConfigureServices on the IHostBuilder, in the case of endpoints that could receive messages immediately on startup, before the web host starts.

**Comment by timbussmann** [comment] 2019-11-21 15:16
> I'm wondering if the DI registration also needs to be moved out of Startup.cs and moved to ConfigureServices on the IHostBuilder, in the case of endpoints that could receive messages immediately on startup, before the web host starts.

Interesting point. Usually, this shouldn't be an issue as long as registrations aren't only usable after the hosted service started (like it is with the message session). All the registrations are happening before the hosted services are started. It's only a problem if a registered dependency needs to be initialized/started somehow as part of the hosted service's startup process.

**Comment by jbogard** [comment] 2019-11-21 15:30
Just hit this yesterday too, and can confirm moving the `ConfigureWebHostDefaults` to the end also worked.

Microsoft's DI container makes quite a few assumptions, including ordering, which isn't obvious.

**Comment by timbussmann** [comment] 2019-11-21 15:50
thanks for confirming that reordering works 👍 

I think it would at least be worthwhile to improve the exception message somehow to indicate that ordering on the host builder can cause this problem.

**Comment by timbussmann** [comment] 2020-03-02 15:57
FYI I raised issue #24 describing the issue a bit in more detail, mentioning the solutions/workarounds and also adding some potential suggestions on how to change this in the future.

I hope you don't mind if I close this issue for now. Please feel free to chime in on #24 if you have some thoughts on that.

**Closed by timbussmann** 2020-03-02 15:57 UTC
